- name: install packages
  hosts: web
  become: yes
  tasks:
   - name: install packages
     ansible.builtin.dng:
       name: "{{ item }}"
       state: latest
     loop: 
     - mysql
     - nginx
     - postfix
