- name: install packages
  hosts: web
  become: yes
  tasks:
   - name: install packages
     ansible.builtin.dnf:
      name: "{{ name.item }}"
      state: "{{ item.state }}"
     loop:
     - { name: 'mysql' , state: 'latest'}
     - { name: 'nginx' , state: 'absent'}
     - { name: 'mysql' , state: 'absent'}